[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "py_auth_rbac"
version = "0.1.0"
description = "Un framework ligero de autenticación y roles"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "bcrypt",
    "pyjwt"
]

[project.urls]
"Homepage" = "https://github.com/bernardodieta/MyFrameworksDevelopments"

[tool.setuptools.packages.find]
where = ["src"]
